export const queryKeys = {
  getStudents: "getStudents",
  getStudent: "getStudent",
  getTeachers: "getTeachers",
  getTeacher: "getTeacher",
  getClasses: "getClasses",
  getClass: "getClass",
  getPayments: "getPayments",
  getPayment: 'getPayment',
  getCourses: 'getCourses',
  getCourse: 'getCourse',
  getClassStudents: 'getClassStudents',
  getTeacherCourses: 'getTeacherCourses',
  getHomeroomCourses: 'getHomeroomCourses',
  getStudentCourses: 'getStudentCourses',
  getCourseStudents: 'getCourseStudents',
  getResults: 'getResults',
  getTeachersBirthday: 'getTeachersBirthday',
  getStudentsBirthday: 'getStudentsBirthday',
  getStudentPayment: 'getStudentPayment',
  getSchool: 'getSchool',
  getBills: 'getBills',
  getStudentBill: 'getStudentBill',
  getStudentsCount: 'getStudentsCount',
  getDebtors: 'getDebtors',
  getClassPins: 'getClassPins',
}
